<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ciir.Core\Ciir.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlogDoFT.Libs.ResultPattern" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
