<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ciir.Core\Ciir.Core.csproj" />
    <ProjectReference Include="..\Ciir.Application\Ciir.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\schemas\ciir.schema.json" LogicalName="Ciir.Serialization.ciir.schema.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
