<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ciir.Application\Ciir.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlogDoFT.Libs.ResultPattern" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ciir.Indexer.Client.Tests" />
  </ItemGroup>

</Project>
