using Microsoft.CodeAnalysis;

namespace Ciir.CSharp.Discovery;

/// <summary>Identifies source files that are generated code and should be excluded from analysis by default.</summary>
internal static class GeneratedCodeDetector
{
    public static bool IsGenerated(SyntaxTree syntaxTree)
    {
        ArgumentNullException.ThrowIfNull(syntaxTree);

        var filePath = syntaxTree.FilePath.Replace('\\', '/');

        if (filePath.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
            filePath.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (filePath.Contains("/obj/", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var leadingTrivia = syntaxTree.GetRoot().GetLeadingTrivia().ToString();
        return leadingTrivia.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
    }
}
